CREATE TABLE "played-it_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "played-it_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "played-it_custom_list_collaborator" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_custom_list_collaborator_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"listId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"canEdit" boolean DEFAULT false NOT NULL,
	"addedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_custom_list_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_custom_list_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"listId" integer NOT NULL,
	"gameId" integer NOT NULL,
	"addedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "played-it_custom_list" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_custom_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text,
	"isPublic" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "played-it_game_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_game_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"gameId" integer NOT NULL,
	"name" varchar(50) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"igdbId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"coverImage" varchar(255),
	"releaseDate" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_group_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_group_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"groupId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"isAdmin" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"description" text,
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "played-it_review_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_review_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"reviewId" integer NOT NULL,
	"voteType" varchar(10) DEFAULT 'like' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_review" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_review_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"gameId" integer NOT NULL,
	"rating" integer NOT NULL,
	"content" text,
	"hasSpoilers" boolean DEFAULT false NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"dislikes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "played-it_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_user_follow" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_user_follow_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"followerId" varchar(255) NOT NULL,
	"followingId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "played-it_user_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "played-it_user_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"gameId" integer NOT NULL,
	"status" varchar(20) NOT NULL,
	"completionStatus" varchar(20) DEFAULT 'not_started' NOT NULL,
	"playtime" integer,
	"startedAt" timestamp with time zone,
	"completedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "played-it_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"username" varchar(255) NOT NULL,
	"name" varchar(255),
	"firstName" varchar(255),
	"lastName" varchar(255),
	"email" varchar(255) NOT NULL,
	"passwordHash" varchar(255),
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"bio" text,
	"preferences" json,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "played-it_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "played-it_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "played-it_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "played-it_account" ADD CONSTRAINT "played-it_account_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_custom_list_collaborator" ADD CONSTRAINT "played-it_custom_list_collaborator_listId_played-it_custom_list_id_fk" FOREIGN KEY ("listId") REFERENCES "public"."played-it_custom_list"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_custom_list_collaborator" ADD CONSTRAINT "played-it_custom_list_collaborator_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_custom_list_item" ADD CONSTRAINT "played-it_custom_list_item_listId_played-it_custom_list_id_fk" FOREIGN KEY ("listId") REFERENCES "public"."played-it_custom_list"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_custom_list_item" ADD CONSTRAINT "played-it_custom_list_item_gameId_played-it_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."played-it_game"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_custom_list" ADD CONSTRAINT "played-it_custom_list_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_game_tag" ADD CONSTRAINT "played-it_game_tag_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_game_tag" ADD CONSTRAINT "played-it_game_tag_gameId_played-it_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."played-it_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_group_member" ADD CONSTRAINT "played-it_group_member_groupId_played-it_group_id_fk" FOREIGN KEY ("groupId") REFERENCES "public"."played-it_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_group_member" ADD CONSTRAINT "played-it_group_member_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_group" ADD CONSTRAINT "played-it_group_createdById_played-it_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_review_vote" ADD CONSTRAINT "played-it_review_vote_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_review_vote" ADD CONSTRAINT "played-it_review_vote_reviewId_played-it_review_id_fk" FOREIGN KEY ("reviewId") REFERENCES "public"."played-it_review"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_review" ADD CONSTRAINT "played-it_review_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_review" ADD CONSTRAINT "played-it_review_gameId_played-it_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."played-it_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_session" ADD CONSTRAINT "played-it_session_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_user_follow" ADD CONSTRAINT "played-it_user_follow_followerId_played-it_user_id_fk" FOREIGN KEY ("followerId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_user_follow" ADD CONSTRAINT "played-it_user_follow_followingId_played-it_user_id_fk" FOREIGN KEY ("followingId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_user_game" ADD CONSTRAINT "played-it_user_game_userId_played-it_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."played-it_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "played-it_user_game" ADD CONSTRAINT "played-it_user_game_gameId_played-it_game_id_fk" FOREIGN KEY ("gameId") REFERENCES "public"."played-it_game"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "played-it_account" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "custom_list_collaborator_unique_idx" ON "played-it_custom_list_collaborator" USING btree ("listId","userId");--> statement-breakpoint
CREATE INDEX "custom_list_collaborator_list_idx" ON "played-it_custom_list_collaborator" USING btree ("listId");--> statement-breakpoint
CREATE INDEX "custom_list_collaborator_user_idx" ON "played-it_custom_list_collaborator" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "custom_list_item_unique_idx" ON "played-it_custom_list_item" USING btree ("listId","gameId");--> statement-breakpoint
CREATE INDEX "custom_list_item_list_idx" ON "played-it_custom_list_item" USING btree ("listId");--> statement-breakpoint
CREATE INDEX "custom_list_item_game_idx" ON "played-it_custom_list_item" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "custom_list_user_idx" ON "played-it_custom_list" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "custom_list_name_idx" ON "played-it_custom_list" USING btree ("name");--> statement-breakpoint
CREATE INDEX "game_tag_user_idx" ON "played-it_game_tag" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "game_tag_game_idx" ON "played-it_game_tag" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "game_tag_name_idx" ON "played-it_game_tag" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "igdb_id_idx" ON "played-it_game" USING btree ("igdbId");--> statement-breakpoint
CREATE INDEX "game_name_idx" ON "played-it_game" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "group_member_unique_idx" ON "played-it_group_member" USING btree ("groupId","userId");--> statement-breakpoint
CREATE INDEX "group_member_group_idx" ON "played-it_group_member" USING btree ("groupId");--> statement-breakpoint
CREATE INDEX "group_member_user_idx" ON "played-it_group_member" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "group_name_idx" ON "played-it_group" USING btree ("name");--> statement-breakpoint
CREATE INDEX "group_created_by_idx" ON "played-it_group" USING btree ("createdById");--> statement-breakpoint
CREATE UNIQUE INDEX "user_review_vote_unique_idx" ON "played-it_review_vote" USING btree ("userId","reviewId");--> statement-breakpoint
CREATE INDEX "review_vote_user_idx" ON "played-it_review_vote" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "review_vote_review_idx" ON "played-it_review_vote" USING btree ("reviewId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_review_unique_idx" ON "played-it_review" USING btree ("userId","gameId");--> statement-breakpoint
CREATE INDEX "review_user_idx" ON "played-it_review" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "review_game_idx" ON "played-it_review" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "played-it_session" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_follow_unique_idx" ON "played-it_user_follow" USING btree ("followerId","followingId");--> statement-breakpoint
CREATE INDEX "user_follow_follower_idx" ON "played-it_user_follow" USING btree ("followerId");--> statement-breakpoint
CREATE INDEX "user_follow_following_idx" ON "played-it_user_follow" USING btree ("followingId");--> statement-breakpoint
CREATE UNIQUE INDEX "user_game_unique_idx" ON "played-it_user_game" USING btree ("userId","gameId");--> statement-breakpoint
CREATE INDEX "user_game_user_idx" ON "played-it_user_game" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_game_game_idx" ON "played-it_user_game" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "user_game_status_idx" ON "played-it_user_game" USING btree ("status");